### ISSUE TITLE
board list view

### ISSUE THREAD

**Issue by Jeongseunghun** [TRIP-SHOT/Front-Tripshot#3]
## 📌Feature Issue
> 게시판 게시글 기능 구현
## 📝To-do
- [x] 게시판 리스트 UX 개선
- [x] 게시글 상세보기 구현
- [x] 게시글 삭제 구현
- [x] 게시글 하트 구현

## ETC
>
