### ISSUE TITLE
UI/UX 개선

### ISSUE THREAD

**Issue by Jeongseunghun** [TRIP-SHOT/Front-Tripshot#7]
## 📌Feature Issue
> 버그 개선, UX 개선
## 📝To-do
- [x] 게시글 컴포넌트 UX 개선
- [ ] 게시글 등록 과정 UX 개선
- [x] 게시글 상세 정보 UX 개선
- [x] 찜 리스트 좋아요 버그 수정
- [x] 좋아요 랭킹 추가
- [ ] 클러스터러 상세 정보

## ETC
>
